version: "3.8"

services:
  app1:
    build: .
    container_name: cine_api_1
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    restart: unless-stopped

  app2:
    build: .
    container_name: cine_api_2
    ports:
      - "127.0.0.1:5001:5000"
    env_file:
      - .env
    restart: unless-stopped