name: Deploy to server with password (rodolfo)

on:
  push:
    branches:
      - servidor1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH (Password)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USER }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          script: |
            cd /apps/cluster_api
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "PORT=5000" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            git pull origin servidor1
            docker-compose down
            docker-compose up --build -d
