name: Deploy to Server with SSH Key (sjar)

on:
  push:
    branches:
      - servidor2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH (SSH Key)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.SERVER2_USER }}
          key: ${{ secrets.SERVER2_SSH_KEY }}
          passphrase: ${{ secrets.SERVER2_SSH_PASSPHRASE }}
          script: |
            cd /apps/cluster_api
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "PORT=5000" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            docker-compose down --remove-orphans
            docker-compose up --build --no-cache -d
            docker-compose up --build -d
